image: tetraweb/php
services:
    - mysql
variables:
    MYSQL_DATABASE: effiocms_db
    MYSQL_USER: effio_user
    MYSQL_PASSWORD: testpassword
    WITH_XDEBUG: "1"
before_script:
    # composer update
    - composer self-update && composer --version
    # setup application
    - apt-get update
    - apt-get install subversion
    - apt-get install libapache2-svn
    - bash bin/install-wp-tests.sh wordpress_test effio_user testpassword localhost 4.3.1
stages:
  - test

test:
  script:
  - php vendor/phpunit/phpunit/phpunit