image: php:5.6-fpm
services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql


before_script:
    - php --version

stages:
  - test

test:PHP5.3:MySQL:
  image: tetraweb/php:5.3
  script:
  - bash bin/install_gitlab_tests.sh wordpress_tests root mysql mysql latest
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit --configuration phpunit.xml

# We test PHP5.6 (the default) with MySQL
test:PHP5.6:MySQL:
  script:
  - bash bin/install_gitlab_tests.sh wordpress_tests root mysql mysql latest
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit --configuration phpunit.xml