image: php:5.6-fpm
services:
  - mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql


before_script:
    - php --version
    - bash bin/install_gitlab_tests.sh wordpress_tests root mysql mysql trunk
stages:
  - test

# We test PHP5.6 (the default) with MySQL
test:mysql:
  script:
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit --configuration phpunit.xml

test:php7:mysql:
  image: php:7
  script:
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit --configuration phpunit.xml