language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - "hhvm"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  # Current $required_php_version for WordPress: 5.2.4
  - "5.2"

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
      
install:
  - composer require phpunit/phpunit:~4.8.0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  # Search plugin for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit
