language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: 
  # Search plugin for PHP syntax errors.
  - find . \( -name '*.php' \) -exec php -lf {} \;
  - phpunit
